language: php
php:
  - 5.6
  - 7.0
before_script:
  - composer install
script: phpunit --coverage-clover=coverage.clover
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --access-token=6f04036dea687dca212a3d7c7dea62ab9f16637b830d7624953dee0131e9b1c4 --format=php-clover coverage.clover